### ISSUE TITLE
Checkout to a particular commit

### ISSUE THREAD

**Issue by Odepax** [FredrikNoren/ungit#1055]
It's easy to checkout to a known branch head or tag using the `Checkout` buttons, but how is it possible (if it is at all) to checkout to a regular commit?

Possibly related: #190.

**Comment by jung-kim** [comment]
So what you can do is that you can create a local branch on the target node and check the newly created branch out.

**Comment by Odepax** [comment]
Ow, that's not wrong!

Though it's a bit a _tricky_ solution for a _"Git made easy"_ tool, nah? What's the reason why UnGit doesn't provide this feature natively?

**Comment by jung-kim** [comment]
Git made easy doesn't mean make all operation easy.  Some operations should be discouraged as it is not a best practice.  What you just described is called detached head state and it is not a good idea to work in such state. [commit with detached head.](http://gitolite.com/detached-head.html) and [how to get out of detached head](https://howtogit.net/recipes/getting-out-of-detached-head-state.html).  

Aside from this being a discouraging operation in general, supporting detached head become another dimensions to many git states ungit manages and it seriously complicates how ungit detects, manages, and transition to and from those states.  This may not make sense to people who didn't open up ungit's code, but we could always work with hash for all operations instead of branch ref but this is bit hard to conceive for me as it is a static ref rather than pointer ref.

**Comment by jung-kim** [comment]
closing for now but feel free to open a new ticket if deemed appropriate
