### ISSUE TITLE
OMG did I just lose four days of work?

### ISSUE THREAD

**Issue by SwingsetTheory** [FredrikNoren/ungit#1199]
I apologize because I may be stupid and this may be all my fault but I'm seriously panicking here.

This is what I did:

![What I Did](https://user-images.githubusercontent.com/4856483/57966425-b3437380-791f-11e9-8ac3-0040964c953f.gif)

In case it's not clear, I opened that menu with the Remote/Branch/Tag checkboxes, and I clicked on the 'Trying-to-recover-from-monotouch-BS' option that had the circles-and-arrow symbol next to it, and then I opened the same menu again but clicked on the option without the circles-and-arrow symbol next to it.

But what you can't see here is that in doing this I seem to have lost 4 days of work!

Before I clicked the option with the circles-and-arrow symbol, I had at least twenty other commits listed in the main branch are. When I clicked that option, they all disappeared!

I must be dumb because I'm sure I did something stupid here, but please please please please tell me there's some way to get all that work back?

I feel sick....

**Comment by SwingsetTheory** [comment]
UPDATE: well I learned a little more basic git knowledge and I was able to manually recover everything from the Terminal so YAY.

That said, I don't know what I did wrong, or why that menu option caused everything to go away, or if there's any way to do the needed kind of recovery through the Ungit UI.

Overall, Ungit is great though.

**Comment by jung-kim** [comment]
So when you the drop down we are workin with displays reference points, tags and branches either local or remote, by clicking on one of them you have switched from your current ref points to another reference points. Which seemingly shows your works has been lost.

Creating more comprehensive feature documentation is bit lacking around here but writing documentations is not exactly a something that inspires me... :P


Ungit is just a tool to make use of another tools easier, which means it can make a mistakes easier as well.  Although git is very good about not loosing data, either via stash or reflogs and etc, I would recommend getting familiar yourself with concept of core git concepts first, such as commit, branch, and local vs remote.

I'm glad you have gotten your work back.  And here are some of my personal recommendations for not loosing works even in command line ungit

1. commit often, you can always squash later if you really want to.
2. when in doubt, create branch and work with branches.
3. don't use force, there are very few limited cases where force is acceptable.

**Comment by SwingsetTheory** [comment]
Ok but I don't think what happened is what's supposed to happen, based on what you just said. Let me explain step by step:

I had a local and a remote version of the same branch. The local version was a whole week's worth of commits ahead of the remote version. I was actually trying to figure out how to push the changes when this mixup happened.

I clicked on the remote branch and, as one would expect, it was in a week-old state. Then I clicked back on the local branch and suddenly *it too* was in the week-old state. All I did was click once to the remote branch, then instantly to the local branch, and it wiped out everything different in the local branch.

I'll attach the reflog here.

<img width="1154" alt="Screen Shot 2019-05-20 at May 20  4 02 06 pm" src="https://user-images.githubusercontent.com/4856483/58048400-b2296680-7b18-11e9-8582-94ad8c43167b.png">

You can see me clicking around to different branches frantically, trying to find where my missing commits are. Luckily I was able to find online reference to manually set the head back to where I was before I lost all that stuff.

If this is the expected behavior, please explain how I could have got my commits back without using the command line.

(By the way I'm not a total noob I've been using git/commits/branches/locals/remotes/pushes/pulls/merges/ etc for years, it's just almost all been through one GUI or another. It's not the concepts I'm unfamiliar with, it's the command line. I think there's just something about how I ask questions that makes people think I don't know anything about what I'm talking about, I guess.)

**Comment by jung-kim** [comment]
Ah! I understand what happened.  So here is a problem, in git you can't really checkout remote, which make sense as it is something that represent a state in remote machine, which means you have two options to move to the remote branch location.

1. checkout via sha1 hash, (this would create "headless" state and this is generally discouraged when using git)
2. create or move a local branch to remote's location and check out newly located local branch.

In Ungits case, what happens when one checkout remote is below (it is this purely from my memory):

```
error := create a new local branch with matching name at the remote's location
if duplicate name error  // local branch with same name exists.
  isYes := Prompt "are you sure?" message
  if isYes 
    Move local branch with same name to remote's location
  else 
    return null
  end if 
else 
  return error
end if
Checkout local branch with same name
return
```

I think that logic maybe broken and it didn't prompt for you.
two additional questions: 
1. can you confirm that you did have local branch with same name as remote branch in this case?
2. Did it prompt "are you sure?" dialog and did you click "yes"

To answer your questions:
1. This is not an intended behavior as in what happened should not have happened without user's explicit consent.  Will fix it later but I'm currently quite busy so I have no ETA for you.
2. As far as better way of asking questions, I have no idea and I myself struggles with that everyday.  But I don't think you are doing a bad job.  To me, a good question is a patient and respectful question irregardless of technical details or approaches.

**Comment by SwingsetTheory** [comment]
1. The branches have the exact same name, I think it shows that in the reflog I included maybe?
2. I don't think there was an "are you sure" question, but my memory is untrustworthy at best. All I can say is I remember I was nervous about doing it but I said to myself, if it was dangerous it wouldn't be this easy to do.

I think though you didn't answer my main question (or else you did and I didn't understand it): is there a way within the ungit GUI that I could have recovered my "lost" commits?

And a supplemental question is: is it possible to push changes to the remotes using the GUI?

**Comment by jung-kim** [comment]
1. reflog shows local but doesn't show the remote's name so I wasn't sure.   but since it is I think current theory explains what happened 
2. Will investigate and fix.

And no, there is currently no way to do that in ungit GUI and showing reflogs or leading nodes without refs gets bit challenging and work with.

Yes you can push to remotes using GUI and here are multiple ways:

1. drag and drop
  - Simply drag and drop remote tag to where you want it to be
2. push operation
  - click local tag
  - and click on "push" that shows to next (this will push the local tag to the selected remote in remote drop down)

**Comment by jung-kim** [comment]
mis click, reopening

**Comment by SwingsetTheory** [comment]
suggestion: titles over those drop-down menus giving a hint as to what they do/what they are

**Comment by SwingsetTheory** [comment]
Followup: a friend walked me through finding the old stuff in the command line and I was able to git it back, ha.
