### ISSUE TITLE
¿Can you add a warnig to move?

### ISSUE THREAD

**Issue by biblioclasta** [FredrikNoren/ungit#473]
Hi,
I love ungit, but "move" has quit an inocent name for such dangerous function.
Can you add a warnig to move? 
Or an option to hide move?

**Comment by ivitivan** [comment]
What does 'move' do? And how can I recover my commits?

**Comment by ivitivan** [comment]
Oh, I found https://github.com/FredrikNoren/ungit/issues/428.
I recovered commits using `git reflog` and `cherry-pick`ing these commits.

**Comment by Ajedi32** [comment]
Yeah, for the record, in the future you can recover any commits lost this way by simply moving the branch back. Even if the commits disappear from ungit's UI they do still exist.

Basically, moving a branch is very similar to a hard reset, which can be recovered from via the following instructions: http://stackoverflow.com/a/27990599/1157054

**Comment by ivitivan** [comment]
Thank you for the information!

**Comment by codingtwinky** [comment]
Just to chime in, just because commit nodes are not showing in ungit, it doesn't mean commits are lost.  In fact, I believe you can recover from any actions in git through git-ref once a change is committed and you are willing to go through the logs.  (Now our resident git expert @Ajedi32 may need to confirm on this...)

Closing as this is not an issue.

**Comment by Ajedi32** [comment]
@codingtwinky Yeah, I did kinda explain that already. Once a change is committed to git, it's very, very hard to lose it. Unless you explicitly tell it to, git won't delete anything from its database that isn't older than two weeks. And that's for content that isn't reachable anywhere, even through reflog. For stuff that is reachable through reflog (and only through reflog), the time is 30 days (by default). And obviously stuff reachable through regular branches and tags is never deleted (since that would kinda defeat the purpose of git).

IMO #124 is the correct way to solve the actual problem being encountered in this issue. Users shouldn't need to use the command line to fix problems they created in the ungit UI.
