### ISSUE TITLE
Git error when trying to see diff on first commit 

### ISSUE THREAD

**Issue by givo** [FredrikNoren/ungit#548]
![untitled](https://cloud.githubusercontent.com/assets/11993599/7356118/d62121da-ed2e-11e4-992a-7d9329bccf9b.png)

when clicking on the first commit and then trying to watch the diff, an error occures.

Windows 7 64bit machine

**Comment by codingtwinky** [comment]
I noticed this few days ago and fixed in the #514.  

Problem was that git doesn't like the `^` revision syntax for the very first commit.  I guess it makes sense since there is no commit before very first commit.  [Fix](https://github.com/FredrikNoren/ungit/pull/514/files#diff-3d97d6a0bc43fe2abcbb34e038981c44R233) for it was to compare the content with `/dev/null` or `NUL` when diff wasn't successful.   This error was suppressed while supporting mix approach between using diff2html and native diff display method.

Interesting difference between win and *nix is that it seems that windows is throwing an error while *nix seems to return a blank response...

**Comment by campersau** [comment]
With #563 the git error is gone and git returns also a blank reponse on windows.

**Comment by FredrikNoren** [comment]
Should be fixed now that #514 is merged
