### ISSUE TITLE
Amazon EC2 ungit web error

### ISSUE THREAD

**Issue by patrickmaciel** [FredrikNoren/ungit#578]
I'm get these erros when I try to access ungit in a amazon ec2 host, redirected using nginx (proxy_pass).

     Unhandled git error!
    Ungit tried to run a git command that resulted in an unhandled error.
    Command

    -c color.ui=false -c core.quotepath=false -c core.pager=cat -c credential.helper="/usr/lib/node_modules/ungit/bin/credentials-helper 0 8448" ls-remote --tags origin
    Error

    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    Stderr

    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    Stdout

**Comment by Ajedi32** [comment]
Sounds to me like `git` can't access the remote repository (`origin`) due to invalid SSH credentials. Are you able to run `git fetch origin` from your ec2 instance?

**Comment by FredrikNoren** [comment]
@patrickmaciel SSH access from a box is a little tricky, since you need to have the key in the keychain (or whatever it's called, sshagent anyway). Best option is to use https instead (on the remote repo, i.e. if you're using GitHub, clone from https:// instead) or second best is to run unigt in a screen and have a sshagent running with the key provided.

Hope that helps.
