### ISSUE TITLE
api/baserepopath not found

### ISSUE THREAD

**Issue by linquize** [FredrikNoren/ungit#579]
In firefox console, I found this error
http://localhost:8448/api/baserepopath HTTP 404

ungit v0.9.2-29-g908c1eb on linux

**Comment by campersau** [comment]
Yes, this is currently the correct behavior see [here](https://github.com/FredrikNoren/ungit/blob/master/source/git-api.js#L514) and is expected see [here](https://github.com/FredrikNoren/ungit/blob/master/components/repository/repository.js#L61-L64).

The method returns a 404 if the current folder is the root of the repo. But if you are in a subfolder / submodule it returns the "base" repo path. I think we should just remove the first traversal [here](https://github.com/FredrikNoren/ungit/blob/master/source/git-api.js#L499) so that the type of the returned value is consistent.

**Comment by FredrikNoren** [comment]
Closing since this is expected behaviour
