### ISSUE TITLE
es6?

### ISSUE THREAD

**Issue by codingtwinky** [FredrikNoren/ungit#669]
Thoughts on [es6](https://nodejs.org/en/docs/es6/)?

I don't think moving client side to es6 is a good idea without babel or something of sort as support on it is very spotty, but I think it make sense for serverside.  I'm a particularly a big fan of arrow functions, map, weakmap, and string templates personally...

(I figure I will continue my strict of continuous refactoring without adding any values...  :P)

**Comment by Ajedi32** [comment]
Yep, ES6 is awesome. In addition to the features you mentioned, I'm also a fan of object destructuring, the class sugar syntax, and async/await (though that's actually part of ES7 I believe).

Babel is also really nice since it frees you from having to constantly worry about backwards compatibility. Even Node doesn't yet support all ES6 features.

**Comment by FredrikNoren** [comment]
I'm all for it, don't mind dropping es5 support on the server side. And
client side with Babel sounds good.

**Comment by codingtwinky** [comment]
Hooray, I think I will dedicate this issue as doing es6 for serverside.  V8 shouldn't need any Babel.  May create separate tickets for doing es6 for client side later.  

Maybe wrap clientside es6 effort and promisify together...

**Comment by codingtwinky** [comment]
Closing as serverside es6 is implemented
