### ISSUE TITLE
LANG and LC_ALL environment variables cause issues with git hooks

### ISSUE THREAD

**Issue by bakkerthehacker** [FredrikNoren/ungit#676]
There are a bunch of git hooks that read the locale from the environment variables.  Ungit has the environment set to `env: { LANG: 'en_US', LC_ALL: 'C' }`.  The `LC_ALL` is ascii here which breaks hooks running on unicode files.

**Comment by codingtwinky** [comment]
One possible solution to this is upgrading forever-monitor and hopefully this problem goes away as this is related to how child nodes are spawned.  The reason why our version of forever-monitor is so behind is due to #531 was an issue for us.  

Still not clear wether issue is fixed or not and need confirmation to work with latest forever-monitor...

**Comment by bakkerthehacker** [comment]
This is not an issue with forever monitor. If I comment the `env` line out of ungit, my pre-commit no longer reports an ascii env. Why does the `env` line exist here in bin/ungit?

**Comment by campersau** [comment]
Just for reference: this was introduced in https://github.com/FredrikNoren/ungit/commit/6e3094e3b57331997ae19de6bd6ee1aad9f57b1c to fix issue https://github.com/FredrikNoren/ungit/issues/176

**Comment by codingtwinky** [comment]
If we want to pass in env variable, this is an issue with how forever monitor pass in process arguments in ascii in unicode env.

**Comment by bakkerthehacker** [comment]
Hmm, if I'm reading the #176 ticket correctly, either of the LANG or LC_ALL variables would have worked here.  I would suggest removing one of them, and setting the other to `'en_US.UTF-8'` for the best compatibility here.
