### ISSUE TITLE
New UI hover effects

### ISSUE THREAD

**Issue by stu177** [FredrikNoren/ungit#688]
The new hover effects in 0.10.0 to me seem to hinder usability. I found the buttons before much easier to use and navigate. Maybe it's just me but wonder if other people feel the same.

**Comment by barbarah** [comment]
I'm also not a great fan of the new UI hover effects. For me the biggest problem is that I cannot see to  which fork I'm pushing to. The fork you push to is the fork selected in the top right, when I hover over the push button the fork name in the top right is hidden. Furthermore the new effects feel a bit messy/chaotic. I don't think it's an improvement.

**Comment by campersau** [comment]
For reference: This behaviour got introduced with https://github.com/FredrikNoren/ungit/pull/550

**Comment by codingtwinky** [comment]
Hmm... I do apologize, and intention was to reduce the overall width of the repository-buttons group's width.    I do agree that having target repo displayed all the time is helpful as push op target is depends on that.  

But do you feel that it is messy/chaotic due to timing of the expansion and reduction or do you not like the this iconized effort at all?

**Comment by chrisuehlinger** [comment]
I'm a big fan of this tool and recommend it to everyone at work (including designers and other people who are not hardcore developers). I recommend it based on its user-friendliness, but also because it takes the words people have heard ("I'll **rebase** that tomorrow", "We need more review before we **merge**", "I **push**ed that on Tuesday") and puts them in a graphical context they can understand. With the words hidden behind hover effects, the value of ungit as a teaching tool is noticeably hindered, and there isn't another tool I can recommend to people instead.

I also love ungit because of its attention to the mobile experience. Hover effects won't work on my iPad, and so if I pull up a repo on my iPad to show someone, they need to already know what the icons mean in order to understand what I'm showing them.

If you guys really feel like there's a need for the hover effects, can you at least add a config option to turn them off (or even make them an opt-in for power users)?

**Comment by daedalus28** [comment]
I am also a huge fan of the tool, and with this update for `patch` support I think it's literally the best git client, period. There's nothing left that I miss from SourceTree or any other client I've used before (except maybe first class support for `git-flow`). 

With that said, I'm afraid I need to second the sentiment regarding the hover effects. In general, "mystery meat" icon navigation only works when the icons are both immediately obvious as to what they represent and also ideally have some precedent in the user's mind for what they ought to do. In the case of ungit, much of the value lies in its accessibility when users may not fully understand what's going on (for example, I've never fully understood rebase until I saw it so clearly laid out in ungit).

I may be a little biased though because on my giant 4K screen there's no need to try to save any space at all :)

**Comment by stu177** [comment]
I'd prefer if they were just buttons with no hover effect, its the way when you hover over something it pushes everything along horizontally so the buttons are always moving all over the place.

**Comment by FredrikNoren** [comment]
Thanks for the feedback everyone! @codingtwinky +1 to fixing this for 0.10.1, thank's for labeling.

Also going forward I think we should try to avoid hover effects in general. We also have hover effects on the branch, submodule and remote drops downs, which I think we could probably solve in a more elegant way without hover effects.

**Comment by codingtwinky** [comment]
I absolutely agree that one of the ungit's most attractive feature is ease of use and help users undestand git.  Hover action does hide details that matters and possibly obscure and confuse.

I will remove hover feature and display full details for all of the buttons.

One quick Q though.  How about setting maximum width to buttons and have it expand on hover for few select buttons?  It is a potential problem that having long branch name can invasive horizontally.  Or is this a miniscule edge case?

**Comment by stu177** [comment]
I think steering clear of hover effects is the best route here. You could truncate extremely long branch names to deal with this issue, but I do think it is quite an edge case and isn't much to worry about.

**Comment by chrisuehlinger** [comment]
Bear in mind that horizontal space is most scarce on mobile/tablet devices, which also (because they are touch-based) can't handle hover effects.

**Comment by stu177** [comment]
I don't think mobile/tablet should be considered as much as desktop in my opinion. I would imagine the majority of ungit users are on a desktop/laptop? I could be wrong though.

**Comment by codingtwinky** [comment]
For "main" view I do think that it would be best to focus on desktop display.

However, I do not want to abandon mobile users and we should [detect mobile device automatically](https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser), which is little crazy, and do serve more mobile specialized view.  

@chrisuehlinger is there any thing you wish to be added or removed for mobile view?  I can't think of any for me now but I don't use ungit on mobile devices.  I can work with you to deliver more customized view for mobiles.

**Comment by FredrikNoren** [comment]
99.88% of all Ungit users (that have enable the google analytics usage tracking) are on desktop, so I think we don't need to put too much effort on mobile just yet :)

**Comment by chrisuehlinger** [comment]
Oh, my point had to do with the fact that ungit works beautifully on mobile as is (before hover effects). I'm certain that I'm in the minority, but I often use ungit from my iPad to conserve screen space on my desktop, and it's awesome.

**Comment by FredrikNoren** [comment]
@chrisuehlinger totally. I also think that designing for touch screens forces things to be simpler too, so think it's good practice to just do it even if the usage doesn't warrant it directly
