### ISSUE TITLE
0.10.2

### ISSUE THREAD

**Issue by FredrikNoren** [FredrikNoren/ungit#755]
Seems like there's a fair amount of fixes in the https://github.com/FredrikNoren/ungit/blob/master/CHANGELOG.md, so I'd suggest getting a new version out.

Wanted to check before we cut a release if there are any last fixes/changes people want to get in?

cc @codingtwinky who knows a lot better than me what's going on :)

**Comment by codingtwinky** [comment]
I do want to get below two done and I think it can be done in a week but none of these are critical.

* [ ] fix for merge commit revert #753 
* [ ] es6ifying entier serverside #754

**Comment by FredrikNoren** [comment]
Ok cool, lets wait a week then and see where we are then

**Comment by Conflate-zz** [comment]
fatal: Unable to create '../../../.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

We keep ketting this error when try to commit, this error we get random

**Comment by codingtwinky** [comment]
That is fixed and described in #515 and it should be released with this tag.  There was potential race condition when executing git operations.

**Comment by icaroo** [comment]
How can I use "Fetch from origin" with password on ssh key?

**Comment by FredrikNoren** [comment]
@codingtwinky want me to wait for #753? Otherwise I can just push it out now and we can do that one for the next release

**Comment by codingtwinky** [comment]
#753 is fixed via #757, which is merged to master now.  

Test is failing and the reason why test is failing is because [git 2.9.0](https://github.com/blog/2188-git-2-9-has-been-released) changed how rename is handled in default.  

I have fix working on it and will send PR for that later but the test failure in #757 shouldn't stop us from punching out a new tag.

**Comment by FredrikNoren** [comment]
Is it just tests that are failing or is ungit actually not working in 2.9.0
though? Might be worth waiting if it's an actual problem

**Comment by codingtwinky** [comment]
#761 fixed it.

Functionality of ungit is not at trouble.  Rather git's default behavior change is at a problem.  Git previously handled file rename as if file deletion and creation with added line and deleted lines.  But in 2.9.0 default behavior changed so that `git status` detects file rename and if file rename is detected does not report line changes.

**Comment by codingtwinky** [comment]
@FredrikNoren #761 is merged and it fixes the 2.9.0 issue and all linux tests are passing.  We are good to cut new one.

**Comment by FredrikNoren** [comment]
Ok, 0.10.2 is now pushed to npm. Good job everyone with getting this release together!
