### ISSUE TITLE
No stash found

### ISSUE THREAD

**Issue by PierreGauthier** [FredrikNoren/ungit#771]
Hi,
Since ungit 0.10.1, every time I change branch or I rebase, ungit try to unstash item.
I don't have this problem when I do it without ungit.

Does anyone know how to prevent ungit to "stash pop" every time ?

Thank you

**Comment by codingtwinky** [comment]
Hi,

Ungit, by default, it will try to stash working items on branch change or rebase and do stash pop when branch change or rebase operation is done, infact ungit does this to many operations.  Now, if you don't want this, you can turn off "autoStashAndPop" and how you can do that is illustrated [here](https://github.com/FredrikNoren/ungit#configuring).  But considering how git operates, disabling this option is generally a bad idea.

For your case, I think underlying issue is something different.  I think somehow ungit went into a bad state and thinking there is a stash to pop when there isn't.  I did quick run down of the changes but I'm unclear to how this could happened.  So could you possibly share more logs or replication steps for me to reproduce this issue?

Thanks,

**Comment by PierreGauthier** [comment]
Hi,
Sorry for my late response.
Indeed it seems to be a bad state of ungit. I tried to install it on an other computer and I don't have the problem. But reinstall ungit doesn't seem sufficient to resolve it on my first computer. I have the problem on all my projects , so is there any config or tmp file that are not delete by 'npm uninstall' ?

And about the steps to reproduce, I don't know how I put ungit in this state, but on any checkout or rebase I get the error.

If I find more information about how to get this state, I'll let you know.

Thank you for your help

**Comment by codingtwinky** [comment]
Ungit doesn't use cached or temporary files, only exception is the .rc file for config, to keep states so reinstalling ungit can't fix the problem.  I would bet that git went into a bad state either by ungit or any other means.  I'd recommend either re-clone or reinitialize git repos.
