### ISSUE TITLE
Expanding a commit extends information off screen/window.

### ISSUE THREAD

**Issue by LukeDWood** [FredrikNoren/ungit#858]
When clicking a commit to view changes the text expands off the left hand side of the screen or window.

I'm running 1.0.0 on Windows 8.1, in Chrome Version 56.0.2924.76

![image](https://cloud.githubusercontent.com/assets/13216206/22551411/9e64aebc-e94c-11e6-94f9-5be6b300a4ae.png)

**Comment by codingtwinky** [comment]
Sorry for taking so long to respond, this was quite tricky to reproduce.  Only way I could recreate this issue for me was to checkout and force git HEAD change.  

When this happens `git-node` has override to correctly draw but but `graph` logic failed to update.  This issue is quite tricky as logic to draw each nodes had to be revisited, which has some parts that I haven't even looked into yet... 

But I think I have the fix and hopefully this was your issue.
