### ISSUE TITLE
Unable to install ungit in node version 8.4.0

### ISSUE THREAD

**Issue by TitaneBoy** [FredrikNoren/ungit#961]
Hi guys..

I'm trying to install ungit with yarn (on Windows) with node version 8.4.0 and I got the following error:

`error forever-monitor@1.1.0: The engine "node" is incompatible with this module. Expected version "0.8.x"`
`error Found incompatible module`

With investigation, I found in the package.json of your module that you are using the version 1.1.0 of forever-monitor module (as the error described before). And within its (forever-monitor) package.json, it use only the version 0.8.x of node, and not higher..

From the version 1.2.1 of forever-monitor module, It uses a version of node higher than 0.8.x.

Is there a reason that you use the version 1.1.0 of this module dependencie ?

Thank you for your help

**Comment by codingtwinky** [comment]
When node 8 came out, packages NPM has some very nasty bugs that prevented installation of some of the c lib dependent lower level libraries, such as phantom, electron and etc.  

Will try to bump the node version and dependencies and give another go at it later.

**Comment by codingtwinky** [comment]
Correction! for this ticket it has nothing to do with npm 5 issue we saw.  Reason why `forever-mointor`  was due to and old bug #531.  Thus we've locked `forever-monitor@1.1.0`.  

This actually has been causing lots of warnings and concerns but it didn't break so we largely left it alone as I don't have a window machine to verify #531 is indeed fixed for us.

I'm going to assume that it is fixed and will do a push.  Can you please verify it is functional in windows?

**Comment by TitaneBoy** [comment]
@codingtwinky It will be a pleasure to test your fixes in Windows but I guess that your fixes is not yet released in npm because the last release of ungit is about 3 weeks.  I will wait until it will be available on npm..

Thanks :-)

**Comment by campersau** [comment]
This is now fixed in ungit version 1.1.33 (see #971).
