### ISSUE TITLE
Show/Ignore Whitespace does not alter diff summary

### ISSUE THREAD

**Issue by stdedos** [FredrikNoren/ungit#969]
Adding a whitespace to a line, typically shows +1 / -1 in diff summary.

I believe that when ignoring whitespace, that should be 0 / 0 - so it both notes that there are changes, just _not important enough_.

It could also help that it applies to full-featured changes (e.g. +9 / -1 ==> +8 / 0)

`git diff --stat (-w)?` shows such differentiation

**Comment by codingtwinky** [comment]
Whit space diff can be turned off via toggling `showing white space diff` button shown below.  And staging also same toggle button for you to use.


<img width="401" alt="screen shot 2018-01-07 at 16 31 47" src="https://user-images.githubusercontent.com/5281068/34656026-46974ef6-f3c8-11e7-842f-8c8032dab138.png">

**Comment by stdedos** [comment]
@codingtwinky "Adding a whitespace to a line, typically shows +1 / -1 in diff summary."

![image](https://user-images.githubusercontent.com/133706/34664322-fb1fba20-f463-11e7-8941-50c2b46673a7.png)
 vs
![image](https://user-images.githubusercontent.com/133706/34664337-04c50904-f464-11e7-9665-477bc7efbb03.png)


So, regardless of the button state, whitespace still shows in the +x / -x summary.
IMHO that should be suppressed (showing `0 / 0` or `0 / 0 (+1 / -1)`

**Comment by jung-kim** [comment]
So this was bit tricky...  In above example, if you were to make any non whitespace change elsewhere in the same file you would see that whitespace change is being not appearing as you wanted.

However, when there is only white space changes and ignore white space is set git would return blank line and that would be received as an invalid result from front end and get ignored and return cached data. 

This is now fixed so that where there is invalid input is returned, we are going to simply assume that there is no diff and display no diff.  I think this is a safe assumption.

**Comment by stdedos** [comment]
Well ... since this is UI, I guess you could do "something better" (as per my recommendation).

Hiding whitespace changes is something only for those pesky commits that involve a lot of whitespace.
However, whitespace needs to be commited finally, along with everything else. Even if whitespace is the only thing commited.

Or doesn't it?

**Comment by jung-kim** [comment]
So let's clarify, what you are suggesting is very specific to when and only when "there is only white space changes" and "-w" flag is set.  Because when there is non white space changes, diff should and will appear whether flag is set or not.

When and only when "there is only white space changes" and "-w" flag is set, it is my understanding that you are suggesting somehow UI should display there is difference but but difference is not significant. 

Isn't this accomplished by the fact that there is a diff in a file, via file appearing in staging, but when you open to see it will display "no diff"?

**Comment by stdedos** [comment]
@jung-kim Mostly, yes.
I was thinking that this should happen in general. So, not only when "there is only white space changes".

Since whitespace "must be" will be commited anyway, I just want to "filter it out of the UI" (use-case: heavy layout refactoring).
And, at the same time, I want to know that there is something that I am not seeing.

So, for example: `+3 / -1 (+1 / -1)`, that would mean that:

There is a `+3 / -1` change, and you are missing `+1 / -1` from ignoring the whitespace.
So, the `git diff --stat` in this case would have been `+4 / -2`, and `git diff --stat` is `+3 / -1`

**Comment by jung-kim** [comment]
Hmm, I'm not sure if I would agreed that always displaying the diff stats for both with and without '-w' flag is valuable.  

Ideally, whitespace changes should be minimal and it is my guesstimate that 9 out of 10 diff stats will be identical.

**Comment by stdedos** [comment]
@jung-kim Well ... it can always be an option in the settings 😄 

> Ideally, whitespace changes should be minimal and it is my guesstimate that 9 out of 10 diff stats will be identical.

Yeah, I know. I have been a "naughty" developer, and now autoformating tools want to teach me how's it done right 😝

**Comment by jung-kim** [comment]
I understand the intention of the idea, however I think it would cause more confusion if two different diff stats are shown and does more harm than good. 

Considering that one can simply click `ignore whitespace` button to see the `-w` flagged diff, I think it should be enough.

**Comment by stdedos** [comment]
As developers wish.

_Close the ticket according to your process_

**Comment by jung-kim** [comment]
Thanks for bringing a bug where '-w' flag resulted in no change wasn't correctly reflected in the UI. 

Which is now fixed in #1008.  Thanks,
